export const FETCH_SAMPLE_DATA = "FETCH_SAMPLE_DATA";
export type FETCH_SAMPLE_DATA = typeof FETCH_SAMPLE_DATA;

export const SAVE_ONBOARDING_DATA = "SAVE_ONBOARDING_DATA";
export type SAVE_ONBOARDING_DATA = typeof SAVE_ONBOARDING_DATA;

export const FETCH_NETWORK = "FETCH_NETWORK";
export type FETCH_NETWORK = typeof FETCH_NETWORK;

export const FETCH_NETWORK_FULFILLED = "FETCH_NETWORK_FULFILLED";
export type FETCH_NETWORK_FULFILLED = typeof FETCH_NETWORK_FULFILLED;

export const FETCH_NETWORK_REJECTED = "FETCH_NETWORK_REJECTED";
export type FETCH_NETWORK_REJECTED = typeof FETCH_NETWORK_REJECTED;

export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export type FETCH_ACCOUNT = typeof FETCH_ACCOUNT;

export const FETCH_ACCOUNT_FULFILLED = "FETCH_ACCOUNT_FULFILLED";
export type FETCH_ACCOUNT_FULFILLED = typeof FETCH_ACCOUNT_FULFILLED;

export const FETCH_ACCOUNT_REJECTED = "FETCH_ACCOUNT_REJECTED";
export type FETCH_ACCOUNT_REJECTED = typeof FETCH_ACCOUNT_REJECTED;

export const FETCH_PRODUCTS_DATA = "FETCH_PRODUCTS_DATA";
export type FETCH_PRODUCTS_DATA = typeof FETCH_PRODUCTS_DATA;
