export const FETCH_SAMPLE_DATA = "FETCH_SAMPLE_DATA";
export type FETCH_SAMPLE_DATA = typeof FETCH_SAMPLE_DATA;

export const SAVE_ONBOARDING_DATA = "SAVE_ONBOARDING_DATA";
export type SAVE_ONBOARDING_DATA = typeof SAVE_ONBOARDING_DATA;

export const FETCH_NETWORK = "FETCH_NETWORK";
export type FETCH_NETWORK = typeof FETCH_NETWORK;

export const FETCH_NETWORK_FULFILLED = "FETCH_NETWORK_FULFILLED";
export type FETCH_NETWORK_FULFILLED = typeof FETCH_NETWORK_FULFILLED;

export const FETCH_NETWORK_REJECTED = "FETCH_NETWORK_REJECTED";
export type FETCH_NETWORK_REJECTED = typeof FETCH_NETWORK_REJECTED;

export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export type FETCH_ACCOUNT = typeof FETCH_ACCOUNT;

export const FETCH_ACCOUNT_FULFILLED = "FETCH_ACCOUNT_FULFILLED";
export type FETCH_ACCOUNT_FULFILLED = typeof FETCH_ACCOUNT_FULFILLED;

export const FETCH_ACCOUNT_REJECTED = "FETCH_ACCOUNT_REJECTED";
export type FETCH_ACCOUNT_REJECTED = typeof FETCH_ACCOUNT_REJECTED;

export const FETCH_ETH_BALANCE = "FETCH_ETH_BALANCE";
export type FETCH_ETH_BALANCE = typeof FETCH_ETH_BALANCE;

export const FETCH_ETH_BALANCE_FULFILLED = "FETCH_ETH_BALANCE_FULFILLED";
export type FETCH_ETH_BALANCE_FULFILLED = typeof FETCH_ETH_BALANCE_FULFILLED;

export const FETCH_ETH_BALANCE_REJECTED = "FETCH_ETH_BALANCE_REJECTED";
export type FETCH_ETH_BALANCE_REJECTED = typeof FETCH_ETH_BALANCE_REJECTED;

export const FETCH_AKT_BALANCE = "FETCH_AKT_BALANCE";
export type FETCH_AKT_BALANCE = typeof FETCH_AKT_BALANCE;

export const FETCH_AKT_BALANCE_FULFILLED = "FETCH_AKT_BALANCE_FULFILLED";
export type FETCH_AKT_BALANCE_FULFILLED = typeof FETCH_AKT_BALANCE_FULFILLED;

export const FETCH_AKT_BALANCE_REJECTED = "FETCH_AKT_BALANCE_REJECTED";
export type FETCH_AKT_BALANCE_REJECTED = typeof FETCH_AKT_BALANCE_REJECTED;

export const FETCH_PORTFOLIO = "FETCH_PORTFOLIO";
export type FETCH_PORTFOLIO = typeof FETCH_PORTFOLIO;

export const FETCH_PORTFOLIO_FULFILLED = "FETCH_PORTFOLIO_FULFILLED";
export type FETCH_PORTFOLIO_FULFILLED = typeof FETCH_PORTFOLIO_FULFILLED;

export const FETCH_PORTFOLIO_REJECTED = "FETCH_PORTFOLIO_REJECTED";
export type FETCH_PORTFOLIO_REJECTED = typeof FETCH_PORTFOLIO_REJECTED;

export const FETCH_COMMITMENT = "FETCH_COMMITMENT";
export type FETCH_COMMITMENT = typeof FETCH_COMMITMENT;

export const FETCH_COMMITMENT_FULFILLED = "FETCH_COMMITMENT_FULFILLED";
export type FETCH_COMMITMENT_FULFILLED = typeof FETCH_COMMITMENT_FULFILLED;

export const FETCH_COMMITMENT_REJECTED = "FETCH_COMMITMENT_REJECTED";
export type FETCH_COMMITMENT_REJECTED = typeof FETCH_COMMITMENT_REJECTED;

export const FETCH_COMMITMENT_PENDING = "FETCH_COMMITMENT_PENDING";
export type FETCH_COMMITMENT_PENDING = typeof FETCH_COMMITMENT_PENDING;

export const FETCH_PRODUCTS_DATA = "FETCH_PRODUCTS_DATA";
export type FETCH_PRODUCTS_DATA = typeof FETCH_PRODUCTS_DATA;

export const SELECT_PRODUCT = "SELECT_PRODUCT";
export type SELECT_PRODUCT = typeof SELECT_PRODUCT;
