export default {
    "onboarding.ageAtRetirement": "Age at retirement",
    "onboarding.annualReturnAssumption": "Annual return assumption",
    "onboarding.briefExplanationOfWhatRewardPointsAre": `Brief explanation of what reward points are, 
    consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna.`,
    "onboarding.comingSoon": "Coming soon",
    "onboarding.continue": "Continue",
    "onboarding.correctBasics": "Correct basics",
    "onboarding.createAPlan": "Create a personal savings plan",
    "onboarding.createEmployeePlan": "Create an employer-matched plan",
    "onboarding.desiredAnnualIncomeAfterRetirement": "Desired annual income after retirement",
    "onboarding.enterAge": "Enter age",
    "onboarding.howMuchIAmSavingPerMonth": "How much I am saving per month",
    "onboarding.inflationCalculationValue": "Inflation calculation value",
    "onboarding.itSeemsYouDonTNeedToSaveAnything": "It seems you don't need to save anything. Are you sure the input you gave is correct?",
    "onboarding.myCurrentAge": "My current age",
    "onboarding.projectedReturns": "Projected returns",
    "onboarding.retirementAge": "Retirement age",
    "onboarding.rewardForStickingToSavingGoals": "Reward for sticking to saving goals",
    "onboarding.section1.desc": "Your ownership of underlying assets is stored immutably on the blockchain.",
    "onboarding.section1.title": "Pension Raid Resistant",
    "onboarding.section2.desc": "All fund managers have a transparent rating based on their past performance.",
    "onboarding.section2.title": "Reliable fund managers",
    "onboarding.section3.desc": "Get rewards for sticking to your savings goals when you stake AKT tokens.",
    "onboarding.section3.title": "Rewards",
    "onboarding.startSaving": "Start saving",
    "onboarding.toEndUpWithAnAnnualPensionOf": "to end up with an annual pension of",
    "onboarding.transparentReputationOfFundManagers": "Transparent reputation of fund managers",
    "onboarding.valueOfMyExistingPensionPots": "Value of existing pension pots",
    "onboarding.youNeedToSave": "You need to save",
};
