export default {
    "onboarding.ageAtRetirement": "Age at retirement",
    "onboarding.annualReturnAssumption": "Annual return assumption",
    "onboarding.briefExplanationOfWhatRewardPointsAre": `Brief explanation of what reward points are, 
    consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna.`,
    "onboarding.continue": "Continue",
    "onboarding.correctBasics": "Correct basics",
    "onboarding.createAPlan": "Create a plan",
    "onboarding.enterAge": "Enter age",
    "onboarding.howMuchIAmSavingPerMonth": "How much I am saving per month",
    "onboarding.inflationCalculationValue": "Inflation calculation value",
    "onboarding.itSeemsYouDonTNeedToSaveAnything": "It seems you don't need to save anything. Are you sure the input you gave is correct?",
    "onboarding.myCurrentAge": "My current age",
    "onboarding.myDesiredAnnualIncomeAfterRetirement": "My desired annual income after retirement",
    "onboarding.projectedReturns": "Projected returns",
    "onboarding.retirementAge": "Retirement age",
    "onboarding.rewardForStickingToSavingGoals": "Reward for sticking to saving goals",
    "onboarding.secureOwnership": "Secure ownership",
    "onboarding.startSaving": "Start saving",
    "onboarding.toEndUpWithAnAnnualPensionOf": "to end up with an annual pension of",
    "onboarding.transparentReputationOfFundManagers": "Transparent reputation of fund managers",
    "onboarding.valueOfMyExistingPensionPots": "Value of my existing pension pots",
    "onboarding.youNeedToSave": "You need to save",
};
