export default {
    "onboarding.ageAtRetirement": "Age at retirement",
    "onboarding.annualReturnAssumption": "Annual return assumption",
    "onboarding.briefExplanationOfWhatRewardPointsAre": `Brief explanation of what reward points are, 
    consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna.`,
    "onboarding.correctBasics": "Correct basics",
    "onboarding.createAPlan": "Create a plan",
    "onboarding.enterAge": "Enter age",
    "onboarding.howMuchIAmSavingPerMonth": "How much I am saving per month",
    "onboarding.inflationCalculationValue": "Inflation calculation value",
    "onboarding.letSCreateYourFirstPortfolio": "Let’s create your first portfolio!",
    "onboarding.myCurrentAge": "My current age",
    "onboarding.myDesiredAnnualIncomeAfterRetirement": "My desired annual income after retirement",
    "onboarding.projectedReturns": "Projected returns",
    "onboarding.retirementAge": "Retirement age",
    "onboarding.rewardForStickingToSavingGoals": "Reward for sticking to saving goals",
    "onboarding.secureOwnership": "Secure ownership",
    "onboarding.startSaving": "Start saving",
    "onboarding.toEndUpWithAPensionValueOf": "to end up with a pension value of",
    "onboarding.transparentReputationOfFundManagers": "Transparent reputation of fund managers",
    "onboarding.tweakGoals": "Tweak goals",
    "onboarding.valueOfMyExistingPensionPots": "Value of my existing pension pots",
    "onboarding.youNeedToSave": "You need to save",
};
