export default {
    "fundAccount.akt": "akt",
    "fundAccount.aktBalance": "AKT balance",
    "fundAccount.downloadMetamaskDesktop": "Download Metamask (desktop)",
    "fundAccount.downloadToshiAppIOsAndroid": "Download Toshi App (iOS / Android)",
    "fundAccount.eth": "eth",
    "fundAccount.ethBalance": "ETH balance",
    "fundAccount.ethObtainedForTest": "ETH obtained for test",
    "fundAccount.every": "Every",
    "fundAccount.forTest": " AKT for test",
    "fundAccount.forThePeriodOf": "For the period of",
    "fundAccount.getFreeEth": "Get free",
    "fundAccount.getFreeEthForTest": "Get free ETH for test",
    "fundAccount.iWillMakeARegularPaymentOf": "I will make a regular payment of",
    "fundAccount.longerCommitmentsMeanMoreRewards": `Longer commitments mean more rewards. 
    If you break your commitment early you will forfeit any rewards accured.`,
    "fundAccount.makeCommitment": "Make commitment",
    "fundAccount.obtainFreeTokensForTest": `Obtain free tokens for test.`,
    "fundAccount.youWillNeedToHaveAnEthereumEnabledBrowserToProceed": "You will need to have an Ethereum enabled browser to proceed.",
};
