export default {
    "fundAccount.akt": "akt",
    "fundAccount.aktBalance": "AKT balance",
    "fundAccount.cancel": `Cancel`,
    "fundAccount.confirm": `Confirm`,
    "fundAccount.confirmContribution": "Confirm contribution",
    "fundAccount.downloadMetamaskDesktop": "Download Metamask (desktop)",
    "fundAccount.downloadToshiAppIOsAndroid": "Download Toshi App (iOS / Android)",
    "fundAccount.eth": "eth",
    "fundAccount.ethBalance": "ETH balance",
    "fundAccount.ethObtainedForTest": "ETH obtained for test",
    "fundAccount.every": "Every",
    "fundAccount.for": "for",
    "fundAccount.forTest": " AKT for test",
    "fundAccount.forThePeriodOf": "For the period of",
    "fundAccount.fullAccessToAkropolis": "Full access to Akropolis",
    "fundAccount.getDiscountsOnFeesAccessToPremiumProducts": 
    "Get discounts on fees, access to premium products and participate in our reward pool by staking AKT tokens.",
    "fundAccount.getFreeEth": "Get free",
    "fundAccount.getFreeEthForTest": "Get free ETH for test",
    "fundAccount.iWillMakeARegularPaymentOf": "I will make a regular payment of",
    "fundAccount.longerCommitmentsMeanMoreRewards": `Longer commitments mean more rewards. 
    If you break your commitment early you will forfeit any rewards accured.`,
    "fundAccount.makeCommitment": "Make commitment",
    "fundAccount.month": "month",
    "fundAccount.obtainFreeTokensForTest": `Obtain free tokens for test.`,
    "fundAccount.stakingTokensMeansThatTheyWillBeLockedUp": "Staking tokens means that they will be locked up for the duration of your commitment period.",
    "fundAccount.theFirstContributionOf": "The first contribution of",
    "fundAccount.willBePaidImmediately": "will be paid immediately.",
    "fundAccount.years": "years",
    "fundAccount.youAreMakingACommitmentToContribute": "You are making a commitment to contribute",
    "fundAccount.youWillNeedToHaveAnEthereumEnabledBrowserToProceed": "You will need to have an Ethereum enabled browser to proceed.",
};
